printWidth: 120
trailingComma: "all"
tabWidth: 4
semi: true
singleQuote: false
bracketSpacing: true
overrides:
    - files: "*.md"
      options:
          proseWrap: "always"
          tabWidth: 2
    - files: "*.sol"
      options:
          printWidth: 120
          tabWidth: 4
          useTabs: false
